#!/usr/bin/env ruby
require './person'
require './student'
require './teacher'
require './book'
require './classroom'
require './corrector'
require './rental'

class App
  def initialize
    @books = []
    @people= []
  end

  def list_all_books
    puts @books
  end

  def list_all_people
    puts @people
  end
end

def main
  app = App.new()

  input = 0
  puts 'Welcome to school library App!'
  puts ''
  while input != '7'
    puts 'Please choose an option by entering a number'
    puts '1 - List all books'
    puts '2 - List all people'
    puts '3 - Create a person'
    puts '4 - Create a book'
    puts '5 - Create a rental'
    puts '6 - List all rentals for given person id'
    puts '7 - Exit'

    input = gets.chomp
    case input
    when '1'
      app.list_all_books
    when '2'
      app.list_all_people
    when '3'
      app.create_person
    when '4'
      app.create_book
    when '5'
      app.create_rental
    when '6'
      app.list_all_rentals
    when '7'
      puts 'Thank you for using this app'
    end
  end
end
main()
