#!/usr/bin/env ruby
require './person'
require './student'
require './teacher'
require './book'
require './classroom'
require './corrector'
require './rental'

class App
  def initialize
    @books = []
    @people= []
    @rentals = []
  end

  def list_all_books
    @books.each do |book|
      puts "Title: \"#{book.title}\", Author: #{book.author}"
    end
  end

  def list_all_people
    @people.each do |person|
      puts "[#{person.class}] Name: #{person.name}, id: #{person.id}, Age: #{person.age}"
    end
  end

  def create_person
    print 'Do you want to create a student (1) or a teacher (2)? [Input the number]: '
    person_class = gets.chomp
    if person_class == '1'
      print 'Classroom: '
      classroom = gets.chomp
      print 'Name: '
      name = gets.chomp
      print 'Age: '
      age = gets.chomp
      print 'Has parent permission? [Y/N]: '
      parent_permission = true if gets.chomp.capitalize == 'Y'
      new_person = Student.new(classroom, name, age, parent_permission)
      @people.push(new_person)
      puts 'Person created succesfully'
      puts ''
    elsif person_class == '2'
      print 'Specialization: '
      specialization = gets.chomp
      print 'Name: '
      name = gets.chomp
      print 'Age: '
      age = gets.chomp
      new_person = Teacher.new(specialization, name, age)
      @people.push(new_person)
      puts 'Person created succesfully'
      puts ''
    end
  end

  def create_book
    print 'Title: '
    title = gets.chomp
    print 'Author: '
    author = gets.chomp
    new_book = Book.new(title, author)
    @books.push(new_book)
    puts 'Book created succesfully'
    puts ''
  end

  def create_rental
    puts 'Select a book from the following list by number'
    @books.map do |book|
      puts "#{@books.index(book)}) Title: #{book.title}, Author: #{book.author}"
    end
    selected_book = gets.chomp
    puts 'Select a person from the following list by number (not id)'
    @people.map do |person|
      puts "#{@people.index(person)}) Name: #{person.name}, Id: #{person.id}, Age: #{person.age}"
    end
    selected_person = gets.chomp
    puts 'Date'
    date = gets.chomp
    new_rental = Rental.new(date, @books[selected_book.to_i], @people[selected_person.to_i])
    @rentals.push(new_rental)
    puts 'Rental created succesfully'
    puts ''
  end

  def list_all_rentals
    puts 'Person Id: '
    person_id = gets.chomp
    rentals_by_person = @rentals.filter {|rental| rental.person.id == person_id.to_i}
    puts 'Rentals: '
    rentals_by_person.each do |rental|
      puts "Date: #{rental.date}, Book: '#{rental.book.title}' by #{rental.book.author}"
    end
    puts ''
  end
end

def main
  app = App.new()

  input = 0
  puts 'Welcome to school library App!'
  puts ''
  while input != '7'
    puts 'Please choose an option by entering a number:'
    puts '1 - List all books'
    puts '2 - List all people'
    puts '3 - Create a person'
    puts '4 - Create a book'
    puts '5 - Create a rental'
    puts '6 - List all rentals for given person id'
    puts '7 - Exit'

    input = gets.chomp
    case input
    when '1'
      app.list_all_books
    when '2'
      app.list_all_people
    when '3'
      app.create_person
    when '4'
      app.create_book
    when '5'
      app.create_rental
    when '6'
      app.list_all_rentals
    when '7'
      puts 'Thank you for using this app'
    end
  end
end
main()
